server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:camunda}
    username: ${DB_USER:camunda}
    password: ${DB_PASSWORD:camunda}
    driver-class-name: org.postgresql.Driver

camunda:
  bpm:
    database:
      type: postgres
    admin-user:
      id: admin
      password: admin
      firstName: Administrator